// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XivMediaPlayer.Server.Models;

#nullable disable

namespace XivMediaPlayer.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260619063752_AddRoomStates")]
    partial class AddRoomStates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("XivMediaPlayer.Shared.Models.MediaTrackRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PlayedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MediaTrackRecords");
                });

            modelBuilder.Entity("XivMediaPlayer.Shared.Models.RoomMediaStateSync", b =>
                {
                    b.Property<string>("LocationKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("DurationMs")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsPlaying")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaylistJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TimecodeMs")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("LocationKey");

                    b.ToTable("RoomMediaStates");
                });

            modelBuilder.Entity("XivMediaPlayer.Shared.Models.RoomState", b =>
                {
                    b.Property<string>("LocationKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DjHeartbeatUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DjOwnerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPlaying")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QueueJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("SpeedRate")
                        .HasColumnType("REAL");

                    b.Property<long>("StateVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TimecodeMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("LocationKey");

                    b.ToTable("RoomStates");
                });

            modelBuilder.Entity("XivMediaPlayer.Shared.Models.TvPlacement", b =>
                {
                    b.Property<string>("LocationKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("PositionX")
                        .HasColumnType("REAL");

                    b.Property<float>("PositionY")
                        .HasColumnType("REAL");

                    b.Property<float>("PositionZ")
                        .HasColumnType("REAL");

                    b.Property<float>("RotationX")
                        .HasColumnType("REAL");

                    b.Property<float>("RotationY")
                        .HasColumnType("REAL");

                    b.Property<float>("RotationZ")
                        .HasColumnType("REAL");

                    b.Property<float>("ScaleX")
                        .HasColumnType("REAL");

                    b.Property<float>("ScaleY")
                        .HasColumnType("REAL");

                    b.HasKey("LocationKey");

                    b.ToTable("TvPlacements");
                });
#pragma warning restore 612, 618
        }
    }
}
